### PR TITLE
feature/qrcode

### PR DESCRIPTION
**Pull request by jneilliii**
add qr code support for the navbar dropdown as configurable option in settings as mentioned in [community forum](https://community.octoprint.org/t/ngrok-tunnel-a-more-secure-but-simple-to-use-alternative-to-port-forwarding/21224/88?u=jneilliii).

image

image

### CODE REVIEW

**Comment by jneilliii** [comment]
need to do some additional testing. looks like the qr code may not be updating properly.

**Comment by fieldOfView** [comment]
Cool, thanks for the PR. Two remarks sofar:

* I would like some margins around the QR code. I think it is even officially required to detect the QR code, but honestly it is just because of aesthetics for me.
* Doesn't OctoPrint ship with the required code to generate QR codes?

**Comment by jneilliii** [comment]
oh good point @fieldOfView it does have QR codes inside the API stuff. I'll look at that and adjust accordingly. I figured out the update issue and will also fix that.

**Comment by jneilliii** [comment]
you're totally right, and it's actually part of the access control plugin, and seems to be the same module library. I'll remove it from the PR and see how it goes.

**Comment by jneilliii** [comment]
should be ready to test Aldo.

image

**Comment by fieldOfView** [comment]
Thanks!

**Pull request merged**
